knpu_oauth2_client:
  clients:
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
    auth-api:
      type: generic
      provider_class: App\AuthApi\AuthApiProvider
      provider_options:
        base_url: "%env(string:AUTH_API_BASE_URL)%"
      client_id: "%env(string:AUTH_API_CLIENT_ID)%"
      client_secret: "%env(string:AUTH_API_CLIENT_SECRET)%"
      redirect_route: connect_auth-api_check
      redirect_params: {}
